package com.modesteam.bazinga.uniques.screens;

public enum ScreenType {
	MAIN_MENU,
	HOW_TO_PLAY, HOW_TO_PLAY__INTRO, HOW_TO_PLAY__TUTORIAL, HOW_TO_PLAY__PAPER, HOW_TO_PLAY__SPOCK,
			HOW_TO_PLAY__ROCK, HOW_TO_PLAY__SCISSORS, HOW_TO_PLAY__LIZARD,
	GAME_SCREEN,
	EXIT_SCREEN,
	NO_SCREEN
}